# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 996d785254aa16e870e0a91f8c731449ab533b3d4d8c22d760577d1a0901c596df2c1c989e6eace99d3fd8bae300d168b7f78547012d61dc3c902e7b8f479149

test:
  secret_key_base: 15b36fa0e292be7f3263525985be207f6b8c6ebafad162c2a5b1a66c58c0590d6e321eaa39947698ac1cbfe509c0720675cbc4735acf6ff69b50cd7ab0e79058

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: '8e75930ea205c9e9ea081daf8d0b7bddaba8e80d634cbcee961a3f661e2ecbe3572a2198ff1923c6a836b9d8cbdd6ff7dbc492bd70f9794776b424601413ff0a'
